# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
## These are used to personalize your new site. If you look in the HTML files,
## you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
## You can create any custom variable you would like, and they will be accessible
## in the templates via {{ site.myvariable }}.
title: mps75
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mps75.net" # the base hostname & protocol for your site, e.g. http://example.com
author:
  twitter: mps75
github_username: mps75
repository: mps75/mps75.net

#assets:
#  sources:
#    - _assets/fonts

# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
#social_link: instagram
#social_username: mps75
twitter_username: mps75
instagram_username: mps75

# Set theme color here
# Choose from: black (default), blue, gray, magenta, orange, red, white, and yellow.
theme_color: black

# Build settings
exclude:
  - drafts
  - scripts
highlighter: rouge
markdown: kramdown
paginate: 3
paginate_path: "/page:num/"
permalink: "/:year/:month/:day/:title"
timezone: "America/Los_Angeles"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap


# Social profiles (for SEO)
social:
  name: Matthew Swanson
  links:
    - https://twitter.com/mps75
    - https://www.linkedin.com/in/mswanson75
    - https://github.com/mps75
    - https://instagram.com/mps75

# Google Analytics
google_analytics: UA-129526774-1